(package "sound-wav"
         "0.02"
         "Play wav file")

(website-url "https://github.com/syohex/emacs-sound-wav")
(keywords "")

(package-file "sound-wav.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "deferred")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
